GET http://localhost:3000/auth/1
Content-Type: application/json

###
GET http://localhost:3000/auth?email=misha@gmail.com
Content-Type: application/json


###
GET http://localhost:3000/auth/whoami
Content-Type: application/json

###
POST http://localhost:3000/auth/signout
Content-Type: application/json


###
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "vova@gmail.com",
  "password": "12345"
}

######
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "vova@gmail.com",
  "password": "12345"
}

###
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "misha@gmail.com",
  "password": "wer12345"
}

###
DELETE http://localhost:3000/auth/1
Content-Type: application/json